services:
  - type: web
    name: sif-ai-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: WEB_CONCURRENCY
        value: 1
      - key: MALLOC_ARENA_MAX
        value: 2
