export const SAMPLE_REPORTS = [
  {
    id: 'OIL-101',
    title: '415V LOTO Isolation Failure at Duliajan Gas Plant',
    category: 'Electrical / LOTO',
    department: 'Electrical',
    location: 'Duliajan Field HQ',
    riskLevel: 'SIF',
    text: 'Technician performed electrical maintenance inside 415V motor control center panel without applying LOTO (Lockout/Tagout) isolation padlocks or testing zero energy state.',
    tags: ['Electrical 415V', 'LOTO Failure', 'Energy Isolation', 'Duliajan'],
  },
  {
    id: 'OIL-102',
    title: 'Unanchored Harness at 12m Pipe Rack - Digboi Refinery',
    category: 'Working at Height',
    department: 'Civil & Height',
    location: 'Digboi Refinery Complex',
    riskLevel: 'SIF',
    text: 'Contractor worker climbed scaffold platform at 12 meters height without securing safety harness lanyard to certified anchor point during pipe rack erection.',
    tags: ['Working at Height', 'Scaffold', 'Fall Protection', 'Digboi'],
  },
  {
    id: 'OIL-103',
    title: 'Hydrocarbon Gas Leak Near Furnace with Active Hot Work',
    category: 'Fire & Gas',
    department: 'Fire & Gas',
    location: 'Digboi Refinery Complex',
    riskLevel: 'SIF',
    text: 'Detected hydrocarbon vapor leak near crude distillation furnace. Portable gas detector alarmed at 35% LEL, while hot work welding permit remained active nearby.',
    tags: ['Gas Leak', 'Hot Work', 'LEL Alarm', 'Furnace'],
  },
  {
    id: 'OIL-104',
    title: 'Damaged Rigging Sling During Heavy Pipe Lift at Rig #7',
    category: 'Mechanical & Lifting',
    department: 'Mechanical & Lifting',
    location: 'Assam Basin Drilling Rig #7',
    riskLevel: 'SIF',
    text: 'Rigging crew attempted 15-ton drill pipe bundle lift using damaged wire rope sling with frayed strands directly under suspended load zone.',
    tags: ['Crane Lifting', 'Frayed Sling', 'Suspended Load', 'Rig #7'],
  },
  {
    id: 'OIL-105',
    title: 'Unmonitored Confined Space Entry at Moran Storage Tank',
    category: 'Confined Space Entry',
    department: 'HSE / Safety',
    location: 'Moran Oil Field',
    riskLevel: 'SIF',
    text: 'Maintenance team entered crude storage tank T-204 without continuous gas testing or dedicated standby attendant posted at manhole entrance.',
    tags: ['Confined Space', 'Storage Tank', 'Gas Testing', 'Moran'],
  },
  {
    id: 'OIL-106',
    title: 'Unsecured Walkway Water Spillage at Jorhat Hub',
    category: 'Housekeeping',
    department: 'HSE / Safety',
    location: 'Jorhat Pipeline Hub',
    riskLevel: 'Non-SIF',
    text: 'Minor water spillage observed on walkway corridor outside workshop room 3. Caution wet floor sign posted and housekeeping notified.',
    tags: ['Water Spill', 'Walkway', 'Housekeeping', 'Jorhat'],
  },
  {
    id: 'OIL-107',
    title: 'Unbuckled Helmet Chin Strap in Material Yard',
    category: 'PPE Inspection',
    department: 'Operations',
    location: 'Duliajan Field HQ',
    riskLevel: 'Non-SIF',
    text: 'Worker observed wearing safety helmet without securing chin strap while carrying light hand tools across pipe storage yard.',
    tags: ['PPE', 'Helmet', 'Chin Strap', 'Storage Yard'],
  }
];

export default SAMPLE_REPORTS;
